import { Account } from '@master-chief/alpaca';

export const accountData: Account = {
  id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa',
  account_number: 'BBBBBBBBBBBB',
  status: 'ACTIVE',
  currency: 'USD',
  buying_power: 200000,
  regt_buying_power: 200000,
  daytrading_buying_power: 0,
  cash: 100000,
  portfolio_value: 100000,
  pattern_day_trader: false,
  trading_blocked: false,
  transfers_blocked: false,
  account_blocked: false,
  created_at: new Date('2021-01-01T00:00:00.000Z'),
  trade_suspended_by_user: false,
  multiplier: 2,
  shorting_enabled: true,
  equity: 100000,
  last_equity: 100000,
  long_market_value: 0,
  short_market_value: 0,
  initial_margin: 0,
  maintenance_margin: 0,
  last_maintenance_margin: 0,
  sma: 100000,
  daytrade_count: 0,
  raw: () => ({
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa',
    account_number: 'BBBBBBBBBBBB',
    status: 'ACTIVE',
    crypto_status: 'ACTIVE',
    currency: 'USD',
    buying_power: '200000',
    regt_buying_power: '200000',
    daytrading_buying_power: '0',
    non_marginable_buying_power: '100000',
    cash: '100000',
    accrued_fees: '0',
    pending_transfer_in: '0',
    portfolio_value: '100000',
    pattern_day_trader: false,
    trading_blocked: false,
    transfers_blocked: false,
    account_blocked: false,
    created_at: '2021-01-01T00:00:00.000Z',
    trade_suspended_by_user: false,
    multiplier: '2',
    shorting_enabled: true,
    equity: '100000',
    last_equity: '100000',
    long_market_value: '0',
    short_market_value: '0',
    initial_margin: '0',
    maintenance_margin: '0',
    last_maintenance_margin: '0',
    sma: '100000',
    daytrade_count: 0,
  }),
};
